tags = ["found footage", "science fiction", "fantasy", "supernatural", "monster", "psychological", "fantasy",
        "zombie", "anthology", "comedy", "body_horror", "slasher", "satire", "romance"]

movies = {"Paranormal Activity": ["found footage", "supernatural"],
          "REC": ["found footage", "zombie"],
          "The Blair Witch Project": ["found footage", "supernatural"],
          "Cloverfield": ["found footage", "monster", "science fiction"],
          "Creep": ["found footage", "psychological"],
          "Trollhunter": ["found footage", "fantasy", "monster"],
          "Willow Creek": ["found footage", "science fiction", "monster"],
          "V/H/S": ["found footage", "anthology", "monster", "supernatural"],
          "Shaun of the Dead": ["comedy", "zombie"],
          "Tremors": ["comedy", "monster", "science fiction"],
          "Ready or Not": ["comedy", "slasher"],
          "Freaky": ["comedy", "slasher"],
          "Fright Night": ["comedy", "monster"],
          "Tucker & Dale vs Evil": ["comedy", "slasher", "satire"],
          "Gremlins": ["comedy", "monster"],
          "Happy Death Day": ["comedy", "slasher"],
          "Friday the 13th": ["slasher"],
          "Halloween": ["slasher"],
          "The Texas Chainsaw Massacre": ["slasher"],
          "Child's Play": ["slasher"],
          "The Fly": ["body_horror", "science fiction"],
          "Tusk": ["body_horror", "comedy"],
          "Eraserhead": ["body_horror"],
          "The Human Centipede": ["body_horror"],
          "The Thing": ["body_horror", "science fiction", "monster"],
          "Hellraiser": ["body_horror", "supernatural"],
          "Slither": ["body_horror", "monster", "science fiction", "comedy"],
          "The Others": ["supernatural", "psychological"],
          "Insidious": ["supernatural"],
          "The Conjuring": ["supernatural"],
          "Alien": ["science fiction", "monster"],
          "Predator": ["science fiction", "monster"],
          "The Blob": ["science fiction", "monster", "body_horror"],
          "Dark Skies": ["science fiction", "monster"],
          "Apollo 18": ["science fiction", "monster", "found footage"],
          "Phoenix Forgotten": ["science fiction", "found footage"],
          "Species": ["science fiction", "monster"],
          "Life": ["science fiction", "monster"],
          "Annihilation": ["science fiction", "monster", "psychological"],
          "Grave Encounters": ["found footage", "supernatural"],
          "Signs": ["science fiction", "monster"],
          "The Cabin in the Woods": ["science fiction", "supernatural", "comedy", "slasher", "satire"],
          "Get Out": ["psychological"],
          "A Nightmare on Elm Street": ["slasher", "supernatural"],
          "The Witch": ["supernatural"],
          "Hereditary": ["supernatural", "psychological"],
          "128 Days Later": ["zombie"],
          "Poltergeist": ["supernatural"],
          "The Babadook": ["supernatural", "psychological"],
          "The Exorcist": ["supernatural"],
          "Train to Busan": ["zombie"],
          "Dawn of the Dead": ["zombie"],
          "Psycho": ["slasher", "psychological"],
          "Scream": ["slasher", "satire"],
          "Trick 'r Treat": ["anthology", "supernatural", "slasher", "comedy"],
          "An American Werewolf in London": ["monster", "comedy"],
          "The Shining": ["supernatural"],
          "You're Next": ["slasher"],
          "IT": ["supernatural", "monster", "slasher"],
          "The Evil Dead": ["supernatural", "monster"],
          "The Lost Boys": ["monster", "comedy"],
          "Final Destination": ["supernatural"],
          "The Mist": ["science fiction", "monster"],
          "Saw": ["slasher", "psychological"],
          "The Silence of the Lambs": ["psychological", "slasher"],
          "Don't Breathe": ["slasher"],
          "The Descent": ["monster"],
          "The Ring": ["supernatural"],
          "The Grudge": ["supernatural"],
          "Let Me In": ["monster", "romance"],
          "Spring": ["monster", "body_horror", "romance"],
          "The Invisible Man": ["science fiction"],
          "Possessor": ["science fiction", "psychological"],
          "Christine": ["supernatural"],
          "Dog Soldiers": ["monster"],
          "Malignant": ["slasher", "body_horror"],
          "Sleepy Hollow": ["slasher", "supernatural", "fantasy"],
          "Creepshow": ["anthology", "comedy"],
          "Tales from the Hood": ["anthology", "comedy"]}