movies = {"Paranormal Activity": ["found footage", "supernatural", "haunting"],
          "REC": ["found footage", "zombie"],
          "The Blair Witch Project": ["found footage", "supernatural"],
          "Cloverfield": ["found footage", "monster", "science fiction"],
          "Creep": ["found footage", "psychological"],
          "Trollhunter": ["found footage", "fantasy", "monster"],
          "Willow Creek": ["found footage", "science fiction", "monster"],
          "V/H/S": ["found footage", "anthology", "monster", "supernatural"],
          "Shaun of the Dead": ["comedy", "zombie"],
          "Tremors": ["comedy", "monster"],
          "Ready or Not": ["comedy", "slasher"],
          "Freaky": ["comedy", "slasher"],
          "Fright Night": ["comedy", "monster"],
          "Tucker & Dale vs Evil": ["comedy", "slasher"],
          "Gremlins": ["comedy", "monster"],
          "Happy Death Day": ["comedy", "slasher"],
          "Friday the 13th": ["slasher"],
          "Halloween": ["slasher"],
          "The Texas Chainsaw Massacre": ["slasher"],
          "Child's Play": ["slasher"],
          "The Fly": ["body horror", "scince fiction"],
          "Tusk": ["body horror", "comedy"],
          "Eraserhead": ["body horror"],
          "The Human Centipede": ["body horror"],
          "The Thing": ["body horror", "science fiction", "monster"],
          "Hellraiser": ["body horror", "supernatural"],
          "Slither": ["body horror", "monster", "science fiction", "comedy"],
          "The Others": ["supernatural", "psychological"],
          "Insidious": ["supernatural"],
          "The Conjuring": ["supernatural"],
          "Alien": ["science fiction", "monster"],
          "Predator": ["science fiction", "monster"],
          "The Blob": ["science fiction", "monster"],
          "Dark Skies": ["science fiction", "monster"],
          "Apollo 18": ["science fiction", "monster", "found footage"],
          "Phoenix Forgotten": ["science fiction", "found footage"],
          "Species": ["science fiction", "monster"],
          "Life": ["science fiction", "monster"],
          "Annihilation": ["science fiction", "monster", "psychological"]}
